# ================================================================
# Vivado batch build for LBTiny on Digilent Nexys A7
# Called by build_bitstream.bat
#
# Usage:
#   vivado -mode batch -source build_bitstream.tcl -tclargs xc7a100tcsg324-1
#   vivado -mode batch -source build_bitstream.tcl -tclargs xc7a100tcsg324-1 persistent
#
# When the second arg is "persistent", the design is built with QSPI
# (SPIx4) configuration properties enabled and an additional .mcs file
# is generated for programming the Nexys A7 on-board Spansion S25FL128S
# QSPI flash. That .mcs survives power cycles and is loaded automatically
# at power-on when the JP1 mode jumper is set to QSPI.
# ================================================================

if {$argc < 1} {
    puts "ERROR: missing FPGA part. Example: vivado -mode batch -source build_bitstream.tcl -tclargs xc7a100tcsg324-1"
    exit 1
}

set part_name  [lindex $argv 0]
set persistent 0
if {$argc >= 2 && [string equal -nocase [lindex $argv 1] "persistent"]} {
    set persistent 1
}
set proj_name  "LBTiny"
set top_name   "lbtiny_top"
set root_dir   [file normalize "."]
set src_dir    [file join $root_dir "src"]
set build_dir  [file join $root_dir "build" $proj_name]

set rtl_files [list \
    [file join $src_dir "lbtiny_mem.v"] \
    [file join $src_dir "lbtiny_viewer.v"] \
    [file join $src_dir "lbtiny_cpu.v"] \
    [file join $src_dir "lbtiny_top.v"] \
]
set mem_file  [file join $src_dir "rom_init.mem"]
set xdc_file  [file join $src_dir "lbtiny.xdc"]

foreach f [concat $rtl_files [list $mem_file $xdc_file]] {
    if {![file exists $f]} {
        puts "ERROR: required file not found: $f"
        exit 1
    }
}

proc check_run_complete {run_name label} {
    set run_obj  [get_runs $run_name]
    set progress [get_property PROGRESS $run_obj]
    set status   [get_property STATUS $run_obj]
    puts "$label status: $status ($progress)"
    if {$progress ne "100%" || ![string match -nocase "*Complete*" $status]} {
        puts "ERROR: $label did not complete successfully."
        puts "ERROR: Run $run_name status was: $status"
        exit 1
    }
}

file mkdir $build_dir
cd $build_dir

foreach path [list \
    [file join $build_dir $proj_name.cache] \
    [file join $build_dir $proj_name.hw] \
    [file join $build_dir $proj_name.ip_user_files] \
    [file join $build_dir $proj_name.runs] \
    [file join $build_dir $proj_name.sim] \
    [file join $build_dir $proj_name.srcs] \
    [file join $build_dir $proj_name.xpr] \
] {
    if {[file exists $path]} { file delete -force $path }
}

create_project $proj_name $build_dir -part $part_name
set_property target_language Verilog [current_project]
set_property default_lib work [current_project]

add_files -norecurse $rtl_files
set_property top $top_name [current_fileset]

add_files -fileset sources_1 -norecurse $mem_file
set mem_obj [get_files $mem_file]
set_property file_type {Memory Initialization Files} $mem_obj
set_property used_in_synthesis true $mem_obj

add_files -fileset constrs_1 -norecurse $xdc_file

if {$persistent} {
    # Extra constraints that tell the bitstream writer to target the
    # Nexys A7 Quad-SPI flash (Spansion S25FL128S). The bitstream itself
    # ends up identical to a JTAG-only build except for the configuration
    # header, but these properties are required so that the FPGA boots
    # correctly from QSPI x4 on power-up.
    set persist_xdc [file join $build_dir "persistent_qspi.xdc"]
    set fh [open $persist_xdc "w"]
    puts $fh "# Auto-generated by build_bitstream.tcl when persistent=1"
    puts $fh "set_property CONFIG_VOLTAGE 3.3              \[current_design\]"
    puts $fh "set_property CFGBVS VCCO                     \[current_design\]"
    puts $fh "set_property BITSTREAM.CONFIG.SPI_BUSWIDTH 4 \[current_design\]"
    puts $fh "set_property BITSTREAM.CONFIG.CONFIGRATE 33  \[current_design\]"
    puts $fh "set_property CONFIG_MODE SPIx4               \[current_design\]"
    puts $fh "set_property BITSTREAM.GENERAL.COMPRESS TRUE \[current_design\]"
    close $fh
    add_files -fileset constrs_1 -norecurse $persist_xdc
    puts "Persistent mode: added $persist_xdc to constraints."
}

update_compile_order -fileset sources_1

launch_runs synth_1 -jobs 4
wait_on_run synth_1
check_run_complete synth_1 "Synthesis"

launch_runs impl_1 -to_step write_bitstream -jobs 4
wait_on_run impl_1
check_run_complete impl_1 "Implementation/bitstream"

set bit_file [file join $build_dir "$proj_name.runs" "impl_1" "$top_name.bit"]
if {![file exists $bit_file]} {
    puts "ERROR: expected bitstream not found: $bit_file"
    exit 1
}

if {$persistent} {
    # Generate an .mcs for the Nexys A7 16 MiB Spansion S25FL128S QSPI flash.
    # interface=spix4, size=16 (MiB), bitstream loaded at offset 0x0.
    set mcs_file [file join $build_dir "$proj_name.runs" "impl_1" "$top_name.mcs"]
    puts "Persistent mode: generating MCS for QSPI flash..."
    puts "  bit_file: $bit_file"
    puts "  mcs_file: $mcs_file"
    if {[catch {
        write_cfgmem -force -format mcs -interface spix4 -size 16 \
            -loadbit "up 0x0 $bit_file" \
            -file $mcs_file
    } result]} {
        puts "ERROR: write_cfgmem failed: $result"
        exit 1
    }
    if {![file exists $mcs_file]} {
        puts "ERROR: expected MCS not found: $mcs_file"
        exit 1
    }
    puts "SUCCESS (persistent): $mcs_file"
    exit 0
}

puts "SUCCESS: $bit_file"
exit 0
